name: CI

on:
  push:
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

jobs:
  efi-shell:
    name: Build Shell.efi
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git uuid-dev iasl nasm python
        shell: bash
      - name: Build Release
        run: |
          ./build.sh
          ls -la build/Shell.efi
        shell: bash
      - name: Archive Shell.efi
        uses: actions/upload-artifact@v3
        with:
          name: efi-shell
          path: build/Shell.efi
